In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/lending-club-loan-data-csv/loan.csv
/kaggle/input/lending-club-loan-data-csv/LCDataDictionary.xlsx

In [ ]:
datos_respaldo = pd.read_csv("/kaggle/input/lending-club-loan-data-csv/loan.csv")

In [7]:
datos = datos_respaldo.copy()

In [8]:
pd.options.display.max_columns = None

In [64]:
datos_filtrados = datos[['emp_length', 'emp_length_num']][datos['emp_length'].isna()]
datos_filtrados

        emp_length  emp_length_num
25             NaN               0
34             NaN               0
41             NaN               0
43             NaN               0
46             NaN               0
...            ...             ...
2260653        NaN               0
2260657        NaN               0
2260659        NaN               0
2260661        NaN               0
2260666        NaN               0

[146907 rows x 2 columns]

In [12]:
datos.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2260668 entries, 0 to 2260667
Data columns (total 145 columns):
 #    Column                                      Dtype
---   ------                                      -----
 0    id                                          float64
 1    member_id                                   float64
 2    loan_amnt                                   int64
 3    funded_amnt                                 int64
 4    funded_amnt_inv                             float64
 5    term                                        object
 6    int_rate                                    float64
 7    installment                                 float64
 8    grade                                       object
 9    sub_grade                                   object
 10   emp_title                                   object
 11   emp_length                                  object
 12   home_ownership                              object
 13   annual_inc                                  float64
 14   verification_status                         object
 15   issue_d                                     object
 16   loan_status                                 object
 17   pymnt_plan                                  object
 18   url                                         float64
 19   desc                                        object
 20   purpose                                     object
 21   title                                       object
 22   zip_code                                    object
 23   addr_state                                  object
 24   dti                                         float64
 25   delinq_2yrs                                 float64
 26   earliest_cr_line                            object
 27   inq_last_6mths                              float64
 28   mths_since_last_delinq                      float64
 29   mths_since_last_record                      float64
 30   open_acc                                    float64
 31   pub_rec                                     float64
 32   revol_bal                                   int64
 33   revol_util                                  float64
 34   total_acc                                   float64
 35   initial_list_status                         object
 36   out_prncp                                   float64
 37   out_prncp_inv                               float64
 38   total_pymnt                                 float64
 39   total_pymnt_inv                             float64
 40   total_rec_prncp                             float64
 41   total_rec_int                               float64
 42   total_rec_late_fee                          float64
 43   recoveries                                  float64
 44   collection_recovery_fee                     float64
 45   last_pymnt_d                                object
 46   last_pymnt_amnt                             float64
 47   next_pymnt_d                                object
 48   last_credit_pull_d                          object
 49   collections_12_mths_ex_med                  float64
 50   mths_since_last_major_derog                 float64
 51   policy_code                                 int64
 52   application_type                            object
 53   annual_inc_joint                            float64
 54   dti_joint                                   float64
 55   verification_status_joint                   object
 56   acc_now_delinq                              float64
 57   tot_coll_amt                                float64
 58   tot_cur_bal                                 float64
 59   open_acc_6m                                 float64
 60   open_act_il                                 float64
 61   open_il_12m                                 float64
 62   open_il_24m                                 float64
 63   mths_since_rcnt_il                          float64
 64   total_bal_il                                float64
 65   il_util                                     float64
 66   open_rv_12m                                 float64
 67   open_rv_24m                                 float64
 68   max_bal_bc                                  float64
 69   all_util                                    float64
 70   total_rev_hi_lim                            float64
 71   inq_fi                                      float64
 72   total_cu_tl                                 float64
 73   inq_last_12m                                float64
 74   acc_open_past_24mths                        float64
 75   avg_cur_bal                                 float64
 76   bc_open_to_buy                              float64
 77   bc_util                                     float64
 78   chargeoff_within_12_mths                    float64
 79   delinq_amnt                                 float64
 80   mo_sin_old_il_acct                          float64
 81   mo_sin_old_rev_tl_op                        float64
 82   mo_sin_rcnt_rev_tl_op                       float64
 83   mo_sin_rcnt_tl                              float64
 84   mort_acc                                    float64
 85   mths_since_recent_bc                        float64
 86   mths_since_recent_bc_dlq                    float64
 87   mths_since_recent_inq                       float64
 88   mths_since_recent_revol_delinq              float64
 89   num_accts_ever_120_pd                       float64
 90   num_actv_bc_tl                              float64
 91   num_actv_rev_tl                             float64
 92   num_bc_sats                                 float64
 93   num_bc_tl                                   float64
 94   num_il_tl                                   float64
 95   num_op_rev_tl                               float64
 96   num_rev_accts                               float64
 97   num_rev_tl_bal_gt_0                         float64
 98   num_sats                                    float64
 99   num_tl_120dpd_2m                            float64
 100  num_tl_30dpd                                float64
 101  num_tl_90g_dpd_24m                          float64
 102  num_tl_op_past_12m                          float64
 103  pct_tl_nvr_dlq                              float64
 104  percent_bc_gt_75                            float64
 105  pub_rec_bankruptcies                        float64
 106  tax_liens                                   float64
 107  tot_hi_cred_lim                             float64
 108  total_bal_ex_mort                           float64
 109  total_bc_limit                              float64
 110  total_il_high_credit_limit                  float64
 111  revol_bal_joint                             float64
 112  sec_app_earliest_cr_line                    object
 113  sec_app_inq_last_6mths                      float64
 114  sec_app_mort_acc                            float64
 115  sec_app_open_acc                            float64
 116  sec_app_revol_util                          float64
 117  sec_app_open_act_il                         float64
 118  sec_app_num_rev_accts                       float64
 119  sec_app_chargeoff_within_12_mths            float64
 120  sec_app_collections_12_mths_ex_med          float64
 121  sec_app_mths_since_last_major_derog         float64
 122  hardship_flag                               object
 123  hardship_type                               object
 124  hardship_reason                             object
 125  hardship_status                             object
 126  deferral_term                               float64
 127  hardship_amount                             float64
 128  hardship_start_date                         object
 129  hardship_end_date                           object
 130  payment_plan_start_date                     object
 131  hardship_length                             float64
 132  hardship_dpd                                float64
 133  hardship_loan_status                        object
 134  orig_projected_additional_accrued_interest  float64
 135  hardship_payoff_balance_amount              float64
 136  hardship_last_payment_amount                float64
 137  disbursement_method                         object
 138  debt_settlement_flag                        object
 139  debt_settlement_flag_date                   object
 140  settlement_status                           object
 141  settlement_date                             object
 142  settlement_amount                           float64
 143  settlement_percentage                       float64
 144  settlement_term                             float64
dtypes: float64(105), int64(4), object(36)
memory usage: 2.4+ GB

In [17]:
datos['term'].unique()

array([' 36 months', ' 60 months'], dtype=object)

In [18]:
datos['term_num'] = datos['term'].str.replace(' months', '')

In [21]:
datos['term_num'].unique()

array([36, 60])

In [20]:
datos['term_num'] = pd.to_numeric(datos['term_num'])

SEGUIMOS PREPROCESANDO DATOS

In [22]:
datos['emp_length'].unique()

array(['10+ years', '6 years', '4 years', '< 1 year', '2 years',
       '9 years', nan, '5 years', '3 years', '7 years', '1 year',
       '8 years'], dtype=object)

In [61]:
datos['emp_length_num'] = datos['emp_length'].replace('< 1 year', '0')
datos['emp_length_num'] = datos['emp_length_num'].str.extract('(\d+)', expand=False)
datos['emp_length_num'] = datos['emp_length_num'] .replace(np.nan, str(0))
datos['emp_length_num'] = pd.to_numeric(datos['emp_length_num'])

In [63]:
datos['emp_length_num'].unique()

array([10,  6,  4,  0,  2,  9,  5,  3,  7,  1,  8])